/// The exception is thrown while getting the list of users.
final class GetUsersException implements Exception {}
